"""Update stale platform findings using checked local acceptance artifacts."""
import json
from pathlib import Path

def apply(findings,src,repos):
    evidence=json.loads((Path(__file__).parent/'platform-acceptance.json').read_text(encoding='utf-8'))
    assert evidence['browser']['expected']==4 and evidence['browser']['unexpected']==0
    assert len(evidence['postgres']['checks'])==4
    by_id={f['id']:f for f in findings}
    def update(id,**values):by_id[id].update(values)
    update('SA01',action='Defensive copies and digest/length checks protect byte identity; production JDBC storage now persists content-addressed bytes and verifies them on read. PostgreSQL recovery and restore checks cover exact bytes.')
    update('SA02',action='Duplicate identities reject in memory and SQL. Database uniqueness and composite foreign keys protect historical ownership and version references.')
    update('SA05',status='Fixed',title='Durable SQL storage now has crash and restore evidence',
           impact='The former memory-only production path could not retain resources across restart.',
           evidence='JDBC repositories and migrations persist metadata and immutable bytes. Pinned PostgreSQL 17.7 passes direct-SQL tenant/version rejection, SIGKILL recovery during an active transaction, and pg_dump restore with exact bytes/findings. H2 repository tests cover publication races and rollback.',
           action='V3 adds composite tenant/version foreign keys. Existing invalid provenance causes migration to fail for investigation. Deployed backups, replication, retention and recovery objectives still require operator acceptance.',
           sources=[src('saas','backend/app/src/main/kotlin/io/hexplain/saas/adapter/jdbc/JdbcRepositories.kt'),src('saas','backend/app/src/main/resources/db/migration/V3__tenant_reference_integrity.sql'),src('saas','tools/test_postgres_acceptance.py'),src('spec','review-2026-09-05/platform-acceptance.json')])
    update('SA06',status='Fixed',title='Workspace authorization derives from authenticated memberships',
           impact='The previous report described an obsolete single-workspace configuration.',
           evidence='OIDC issuer plus subject selects memberships; viewer mutations, foreign identifiers, conflicting selectors and identical subjects from another issuer are rejected. Database constraints independently reject cross-tenant graph edges.',
           action='Hosted identity uses OIDC; form credentials are limited to test/demo. Membership provisioning, real identity-provider login and distributed quotas remain deployment acceptance tasks.',
           sources=[src('saas','backend/app/src/main/kotlin/io/hexplain/saas/config/Memberships.kt'),src('saas','backend/app/src/main/kotlin/io/hexplain/saas/config/SecurityConfig.kt'),src('saas','backend/app/src/test/kotlin/io/hexplain/saas/TenantAccessTest.kt')])
    update('SA03',action='Parsing budgets are supplemented by isolated JVM requests, bounded request/response messages, per-process admission and per-workspace active-request limits, forced deadlines and credential stripping. Native adapter Linux containment remains separate from hosted routing; distributed quotas and production load remain unverified.',
           sources=by_id['SA03']['sources']+[src('saas','backend/app/src/main/kotlin/io/hexplain/saas/worker/IsolatedFormatEngine.kt'),src('saas','backend/app/src/test/kotlin/io/hexplain/saas/WorkerIsolationTest.kt')])
    update('SA07',status='Scoped mitigation',title='Real browser checks exposed and fixed contrast and keyboard gaps',
           evidence='Three Chromium tests pass at 390/1440 pixels and in the byte viewer. Axe WCAG A/AA scans have zero detected violations in these states. Skip-link focus, keyboard tree expansion, pagination and responsive screenshots are verified with controlled API fixtures.',
           action='Raised muted-text contrast, added a skip link and keyboard-focusable table regions. Real OIDC/backend browser integration, human screen-reader walkthroughs and production concurrent-run latency remain unverified.',
           sources=[src('saas','frontend/browser-tests/accessibility.spec.ts'),src('saas','frontend/app/globals.css'),src('saas','frontend/app/layout.tsx'),src('spec','review-2026-09-05/platform-acceptance.json')])
    update('EN11',status='Documented deviation',title='Signed 24-bit TIFF retains the correct signed contract',
           action=by_id['EN11']['action'].replace('17?31','17–31')+' This is a bounded upstream compatibility deviation, not an unresolved Hexplain signedness defect.')
    update('SP06',action='The pinned GDAL 3.13.3 image independently verifies nine TIFF semantic datasets, one selected CF variable and both XYZ features. TIFF alpha/internal masks and precedence are measured. HDF-EOS, broader CF, external masks and wider variants remain explicit exclusions; signed-24-bit compatibility remains a non-pass.')

    update('SA03', action='Isolated workers now acquire PostgreSQL session advisory locks shared across replicas: one active request per workspace and two global slots. Real JDBC probes verify exclusion, reuse and lost-session rejection; worker tests verify release on launch failure and deadlines beginning before preparation. Session-preserving database connections are required. Rate quotas, network-partition behavior and deployed load acceptance remain open.', sources=by_id['SA03']['sources']+[src('saas','backend/app/src/main/kotlin/io/hexplain/saas/worker/PostgresAdmission.kt'),src('saas','backend/app/src/test/kotlin/io/hexplain/saas/PostgresAdmissionProbe.kt')])
    update('SA07', evidence=by_id['SA07']['evidence']+' A fourth Chromium test verifies the configured session cookie survives a cross-site top-level GET callback. SameSite=Lax fixes the Strict policy that could lose the saved authorization request.', sources=by_id['SA07']['sources']+[src('saas','frontend/browser-tests/oidc-cookie.spec.ts'),src('saas','backend/app/src/main/resources/application.yml')])
    update('SP07', evidence=by_id['SP07']['evidence']+' Thirteen new opt-in security-profile cases pass in pySHACL and Apache Jena, including controlled concepts, cardinality, dates and compound scope. These shapes do not implement authorization or implicit inheritance.', sources=by_id['SP07']['sources']+[src('spec','specification/validation/test/security-profile.ttl'),src('spec','tools/test_security_profile.py')])
    update('SP08', status='Blocked externally', action='Live probes return HTTP 200 text/html with identical bodies for the security namespace and immutable release manifest. Configure the hosting routes and media negotiation, then pass the new live publication workflow. Local snapshot validation does not close this deployment defect.', sources=by_id['SP08']['sources']+[src('spec','review-2026-09-05/live-publication.json'),src('spec','tools/check_live_publication.py')])
    update('EN09', status='Blocked externally', action=by_id['EN09']['action']+' GitHub Actions run 34038098217 did not start any test steps: account payment/spending-limit restrictions blocked execution. Account-owner billing resolution is required before remote acceptance can run.', sources=by_id['EN09']['sources']+[src('spec','review-2026-09-05/remote-ci.json')])

    update('SP07', title='Bit-packing and compound competency gaps now have shared regressions', evidence='The retained semantic corpora are supplemented by 13 security cases and 47 new layout/compound cases passing in pySHACL and Apache Jena without inference or rule execution. The fractional packed-width counterexample passed before correction. Tests cover integer boundaries, fixed/dynamic widths, bit order, nested required roles, primary typing and count contradictions.', action='DLV and Bundle 1.1 reject fractional layout quantities and part counts; generated references and migration notes are updated. The security/bit-packing/compound increment is implemented. Independent ontology review and equivalent depth across all vocabulary combinations remain outstanding.', sources=[src('spec','tools/test_layout_competency.py'),src('spec','specification/validation/competency-depth.html'),src('spec','review-2026-09-05/layout-competency.json'),src('spec','specification/reference/boundary-revision.md'),src('spec','tools/test_security_profile.py')])

    update('SP08', evidence=by_id['SP08']['evidence']+' New draft 2026-09-06.1 pins 41 files including DLV/Bundle 1.1 and security/layout competency corpora. Archived/current replay now covers these suites as well.', sources=by_id['SP08']['sources']+[src('spec','releases/2026-09-06.1/manifest.json'),src('spec','tools/test_release_contract.py')])

    update('SP07', evidence=by_id['SP07']['evidence'].replace('47 new layout/compound cases','52 layout/compound cases')+' Five added cases reproduce and fix primary-only required membership and reject literal/untyped compound members.', action=by_id['SP07']['action']+' Bundle 1.2 follows primaryPart explicitly in required-role checks with inference disabled; Asset member typing is now enforced. Missing external profile definitions and independent ontology review remain explicit evidence limits.')

    update('EN07', evidence=by_id['EN07']['evidence']+' Nine terminated-field regressions add literal wire vectors, empty and UTF-8 payloads, counted element extents, budget rejection, unsupported numeric rejection and 434 independent short-binary first-occurrence comparisons.', action=by_id['EN07']['action'].replace('and some inferred-length forms still reject','still reject')+' Terminator-inclusive automatic lengths now work for byte/string payloads without fixedValue. Ambiguous embedded or boundary-overlapping terminators reject in linear time; encoded struct terminators remain unsupported.', sources=by_id['EN07']['sources']+[src('engine','core/src/test/kotlin/io/hexplain/core/metacodec/WriterTerminatedLengthTest.kt'),src('spec','review-2026-09-05/terminated-writer.json')])

    update('SP06', evidence=by_id['SP06']['evidence']+' Fresh pinned GDAL 3.13.3 adds 112 generated ISO-WKB cases and 60 GeoPackage rows across XY/XYZ/XYM/XYZM, all seven simple-feature families, empty/null geometry and exact 64-bit attributes. Subset-envelope comparisons exposed and fixed XYZM handling.', action=by_id['SP06']['action']+' Vector evidence now covers the seven ISO-WKB families and one generated GeoPackage container. Native Shapefile/FlatGeobuf/GeoParquet, reprojection, topology and broader upstream vector fixtures remain unmeasured.', sources=by_id['SP06']['sources']+[src('spec','specification/coverage/gdal-tests/vector-depth.html'),src('spec','review-2026-09-05/vector-depth.json')])
    update('SP07', action=by_id['SP07']['action']+' A hash-pinned independent-review candidate now covers 737 resources in 35 modules, with a module checklist and explicit reviewer/disposition requirements. Review is pending; the preparation is not external approval.', sources=by_id['SP07']['sources']+[src('spec','specification/ontology-review/review-manifest.json'),src('spec','specification/ontology-review/review-instructions.md')])
