gradle.projectsEvaluated {
    def app = gradle.rootProject.findProject(':backend:app')
    if (app != null) {
        app.dependencies.add('testImplementation', 'io.hexplain:core')
        app.dependencies.add('testImplementation', 'org.apache.jena:jena-core:5.5.0')
        app.kotlin.sourceSets.test.kotlin.srcDir('D:/work/hexplain.io/review-2026-09-05')
    }
}
