"""Canonical local namespace routes; generation and server checks share this inventory."""
from pathlib import Path
from rdflib import OWL, RDF, Graph
from _family import family_paths

ROOT = Path(__file__).resolve().parents[1]


def routes():
    result = {}
    for path in family_paths(ROOT/"specification"):
        file = Path(path)
        graph = Graph().parse(file, format="turtle")
        for ontology in graph.subjects(RDF.type, OWL.Ontology):
            for iri in [ontology, *graph.objects(ontology, OWL.versionIRI)]:
                if str(iri).startswith("https://hexplain.io/ns/"):
                    route = str(iri).removeprefix("https://hexplain.io")
                    if route in result and result[route] != file:
                        raise ValueError(f"Duplicate ontology route: {route}")
                    result[route] = file
    return result


def render():
    lines = ["# Generated by tools/_publication.py; local configuration only.", "server {", "  listen 8080;", "  server_name _;", "  root /srv/hexplain;", "  index index.html;", "  server_tokens off;", "  location ~ /\\. { deny all; }"]
    for route, file in sorted(routes().items()):
        relative = file.relative_to(ROOT).as_posix()
        page = file.parent.relative_to(ROOT).as_posix()+"/index.html"
        lines.extend([f"  location = {route} {{", "    types { }", "    default_type text/turtle;", f"    alias /srv/hexplain/{relative};", "    add_header X-Content-Type-Options nosniff always;", f'    add_header Link "</{page}>; rel=describedby" always;', "  }"])
    lines += ["  location /ns/ { return 404; }", "  location /releases/ { try_files $uri $uri/ =404; }", "  location / { try_files $uri $uri/ =404; }", "}"]
    return "\n".join(lines)+"\n"


if __name__ == "__main__":
    (ROOT/"deployment/publication.conf").write_text(render(), encoding="utf-8")
    print(f"Generated {len(routes())} ontology and version routes")
