"""An optional strict profile: closed Field and Struct shapes, and a term lint of engine profiles.

The family's shapes are open, as SHACL shapes normally are: a Field may carry any extra
property. That is the right default for the specification, and the wrong one for a profile
author who wants to know that `bddo:sizeFromFeild`, or an aspect property put directly on a
Field instead of behind hexplain:mapsToProperty, is not doing anything. The strict profile,
specification/validation/test/strict-profile-shapes.ttl, closes bddo:Field and bddo:Struct
(sh:closed) over the properties the physical, core and layout vocabularies define plus the
documentation annotations. It is generated from the family (run with --write after adding a
property) and is NOT part of the family: a processor applies it only when asked to.

When HEXPLAIN_TOOLS names a checkout of the reference engine, every profile Turtle file under
it (outside build directories) is also linted, read-only: every Hexplain term it uses must be
defined by the family (as tools/test_known_terms.py does for this repository's data), and it
must conform to the strict profile. Without HEXPLAIN_TOOLS that part is not run, and the
gate says so; it does not report SKIP, because the strict profile's own checks still run.
"""
import os
import sys
from pathlib import Path

from pyshacl import validate
from rdflib import OWL, RDF, RDFS, Graph, Namespace, URIRef
from rdflib.collection import Collection

import specgraph
from test_known_terms import owned_namespaces, unknown_terms

ROOT = Path(__file__).resolve().parents[1]
TARGET = ROOT / "specification/validation/test/strict-profile-shapes.ttl"
SH = Namespace("http://www.w3.org/ns/shacl#")
NAMESPACES = ["https://hexplain.io/ns/bddo#", "https://hexplain.io/ns/core#", "https://hexplain.io/ns/dlv#"]
ANNOTATIONS = [RDF.type, RDFS.label, RDFS.comment, RDFS.seeAlso, RDFS.isDefinedBy, OWL.deprecated,
               URIRef("http://www.w3.org/2004/02/skos/core#definition"),
               URIRef("http://www.w3.org/2004/02/skos/core#scopeNote"),
               URIRef("http://www.w3.org/2004/02/skos/core#note"),
               URIRef("http://www.w3.org/2004/02/skos/core#editorialNote"),
               URIRef("http://www.w3.org/2004/02/skos/core#historyNote"),
               URIRef("http://www.w3.org/2004/02/skos/core#changeNote"),
               URIRef("http://purl.org/dc/terms/description"), URIRef("http://purl.org/dc/terms/source")]
PREFIX = "https://hexplain.io/ns/validation/strict#"


def allowed(family):
    props = {p for t in (RDF.Property, OWL.ObjectProperty, OWL.DatatypeProperty, OWL.AnnotationProperty)
             for p in family.subjects(RDF.type, t) if any(str(p).startswith(n) for n in NAMESPACES)}
    return sorted(props, key=str) + ANNOTATIONS


def render(family):
    props = allowed(family)
    listed = "\n        ".join(p.n3() for p in props)
    out = ["# Generated by tools/test_strict_profile.py --write from the specification family. Do not edit.",
           "# An OPTIONAL strict profile: it closes bddo:Field and bddo:Struct over the properties the",
           "# physical, core and layout vocabularies define plus documentation annotations. It is not part",
           "# of the family; apply it only to catch misspelt or misplaced properties in a profile.",
           "@prefix sh: <http://www.w3.org/ns/shacl#> .",
           f"@prefix strict: <{PREFIX}> .", ""]
    for cls in ["Field", "Struct"]:
        out += [f"strict:Closed{cls}Shape a sh:NodeShape ;",
                f"    sh:targetClass <https://hexplain.io/ns/bddo#{cls}> ;",
                "    sh:closed true ;",
                f"    sh:message \"A bddo:{cls} carries only properties of bddo, core or dlv and documentation "
                "annotations; map a semantic property with hexplain:mapsToProperty.\" ;",
                "    sh:ignoredProperties (",
                "        " + listed,
                "    ) .", ""]
    return "\n".join(out)


def engine_profiles(root):
    for path in sorted(root.rglob("*.ttl")):
        parts = set(path.parts)
        if parts & {"build", "build-root", ".gradle", "node_modules", "out"}:
            continue
        if "profile" in path.name or "profiles" in parts:
            yield path


def main():
    family = specgraph.ontologies()
    expected = render(family)
    if "--write" in sys.argv:
        TARGET.write_text(expected, encoding="utf-8", newline="\n")
    if TARGET.read_text(encoding="utf-8") != expected:
        print("FAIL: strict-profile-shapes.ttl is stale; run python tools/test_strict_profile.py --write")
        sys.exit(1)
    strict = Graph().parse(data=expected, format="turtle")
    ignored = set(Collection(strict, strict.value(URIRef(PREFIX + "ClosedFieldShape"), SH.ignoredProperties)))
    probe = Graph().parse(format="turtle", data="""@prefix bddo: <https://hexplain.io/ns/bddo#> .
        @prefix araster: <https://hexplain.io/ns/aspect/raster#> .
        <urn:f> a bddo:Field ; bddo:dataType bddo:uint8 ; araster:width 3 .
        <urn:g> a bddo:Field ; bddo:dataType bddo:uint8 ; bddo:size 1 .""")
    ok, report, _ = validate(probe, shacl_graph=strict, inference="none")
    assert not ok and len(set(report.subjects(RDF.type, SH.ValidationResult))) == 1, \
        "the strict profile must reject an aspect property on a Field and accept a plain one"
    failures = []
    engine = os.environ.get("HEXPLAIN_TOOLS")
    checked = 0
    if engine:
        root = Path(engine)
        if not root.is_dir():
            print(f"FAIL: HEXPLAIN_TOOLS={engine} is not a directory")
            sys.exit(1)
        known = set(family.subjects())
        namespaces = owned_namespaces(family)
        for path in engine_profiles(root):
            try:
                g = Graph().parse(data=path.read_text(encoding="utf-8"), format="turtle")
            except Exception as exc:  # a profile that is not Turtle is the engine's concern
                failures.append(f"{path}: does not parse ({exc.__class__.__name__})")
                continue
            checked += 1
            for iri in unknown_terms(g, known, namespaces):
                failures.append(f"{path}: {iri} is not defined by any family module")
            conforms, _, text = validate(g, shacl_graph=strict, inference="none")
            if not conforms:
                failures.append(f"{path}: does not conform to the strict profile:\n{text[:1500]}")
    if failures:
        print("FAIL:\n  " + "\n  ".join(failures))
        sys.exit(1)
    tail = (f"; {checked} engine profiles under HEXPLAIN_TOOLS use only family terms and conform to it"
            if engine else "; engine profiles not linted (set HEXPLAIN_TOOLS to an engine checkout to lint them)")
    print(f"PASS: strict profile closes Field and Struct over {len(ignored)} properties and is current{tail}")


if __name__ == "__main__":
    main()
